using Net5Console;
using System;
using System.Net.Http;
using System.Threading.Tasks;

/**
 * You can simplify the entry point of a console application thanks to the new top-level statements feature. 
 * That enables you to remove any reference to the namespace, class and main method
 */

Console.WriteLine("Hello!");
Console.WriteLine("------------------------------");
Console.WriteLine("Type 1 and press enter if you want to play with records");
Console.WriteLine("Type 2 and press enter if you want to play with API");
Console.WriteLine("Press any other button to escape");

string choice = Console.ReadLine();

switch (choice)
{
    case "1":
        var records = new RecordsOverview();
        records.InitRecord();
        break;
    case "2":
        swaggerClient client = new("https://localhost:44379", new HttpClient());
        var news = await client.NewsFeedAsync();
        if (news != null)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"{news.Title}");
            foreach (var item in news.Modules)
            {
                Console.WriteLine($"{item.Title}");

                if (item.Stories.Count > 0)
                {
                    foreach (var story in item.Stories)
                    {
                        System.DateTime dateTime = new System.DateTime(1970, 1, 1, 0, 0, 0, 0);
                        dateTime = dateTime.AddSeconds(story.Published);

                        Console.ForegroundColor = ConsoleColor.Red;
                        Console.WriteLine($"- Title:\n- {story.Title}\n");
                        Console.ForegroundColor = ConsoleColor.Green;
                        Console.WriteLine($"- Published:\n- {dateTime}\n");
                        Console.ForegroundColor = ConsoleColor.White;
                        Console.WriteLine($"- Summary:\n- {story.AutoGeneratedSummary}\n");
                        Console.ForegroundColor = ConsoleColor.Cyan;
                        Console.WriteLine($"- Read the full article:\n- {story.ShortURL}");
                        Console.ResetColor();
                        Console.WriteLine("\n------------------------------");
                    }
                }
            }
        }

        break;
    default:
        return;
}


