using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Net5Api
{

    public class News
    {
        public string title { get; set; }
        public Module[] modules { get; set; }
    }

    public class Module
    {
        public string id { get; set; }
        public object title { get; set; }
        public string type { get; set; }
        public Story[] stories { get; set; }
    }

    public class Story
    {
        public string id { get; set; }
        public string internalID { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public string autoGeneratedSummary { get; set; }
        public string[] _abstract { get; set; }
        public int published { get; set; }
        public int updatedAt { get; set; }
        public int wordCount { get; set; }
        public string[] secondaryBrands { get; set; }
        public string byline { get; set; }
        public string shortURL { get; set; }
        public string longURL { get; set; }
        public string primaryCategory { get; set; }
        public string primarySite { get; set; }
        public string eyebrowSite { get; set; }
        public Reading[] readings { get; set; }
        public string image { get; set; }
        public string thumbnailImage { get; set; }
        public string card { get; set; }
    }

    public class Reading
    {
        public string url { get; set; }
        public string voice { get; set; }
        public int durationMs { get; set; }
    }
}
